[package]
name = "cambridge-thesis"
version = "0.1.0"
entrypoint = "cambridge.typ"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
license = "MIT"
description = "Thesis template for the University of Cambridge"
repository = "https://github.com/jeffa5/typst-cambridge"
